name: Test UBSan

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - .mailmap
      - '**.md'
      - AUTHORS
      - doc/**
      - .github/**
      - '!.github/workflows/test-ubsan.yml'
  push:
    branches:
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - .mailmap
      - '**.md'
      - AUTHORS
      - doc/**
      - .github/**
      - '!.github/workflows/test-ubsan.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test-ubsan:
    # if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    env:
      CC: sccache clang
      CXX: sccache clang++
      LINK: sccache clang++
      CONFIG_FLAGS: --enable-ubsan
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Store suppressions path
        run: |
          echo "UBSAN_OPTIONS=suppressions=$GITHUB_WORKSPACE/suppressions.supp:report_error_type=1:print_stacktrace=1" >> $GITHUB_ENV
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@054db53350805f83040bf3e6e9b8cf5a139aa7c9  # v0.0.7
        with:
          version: v0.9.1
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1
      - name: Test
        run: make run-ci -j2 V=1 TEST_CI_ARGS="-p actions -t 300 --measure-flakiness 9"
